#!/bin/bash

cd "$(dirname "$(readlink -en "$0")")"

pgrep -x lgtd_sync > /dev/null
if [ $? -ne 0 ]
then
	./lgtd_sync --daemon
	if [ $? -ne 0 ]
	then
		echo "warning: could not start lgtd_sync"
	fi
fi

pgrep -x lgtd_d > /dev/null
if [ $? -ne 0 ]
then
	./lgtd_d --daemon
	if [ $? -ne 0 ]
	then
		echo "problem starting lgtd_d, aborting"
		exit 1
	fi
fi

exec ./lgtd_ui
